BMP - overcooking kodu
grupacosmo/rocket-playground pull request #17
Opened 2024-03-13 19:25 UTC by KajSob

struct, namespace i inne takie bardzo super rzeczy żeby kod był overcooked

2024-03-15 03:16 UTC, Bartosz-Slowik commented
git checkout master
git pull
git checkout bmp
git merge master

rozwiąż konflikty jesli jakies zostaną

2024-03-15 03:25 UTC, Bartosz-Slowik requested changes
Dobrze napisany kod, jeśli wszyscy tak będą pisać to może poleci

2024-03-15 03:25 UTC, Bartosz-Slowik commented on projects/bmp/src/bmp.cpp
> +  delay(2000);
move this delay to loop

2024-03-15 03:25 UTC, Bartosz-Slowik commented on projects/bmp/include/bmp.hpp
> +//wymaga ustawienia Wire.begin(SDA_PIN, SCL_PIN) wcześniej
Require i2c setup

2024-03-15 03:25 UTC, Bartosz-Slowik commented on projects/bmp/src/bmp.cpp
> +//korzystanie z Adafruit BMP280 Library by Adafruit
eng

2024-03-15 03:25 UTC, Bartosz-Slowik commented on projects/bmp/src/bmp.cpp
> +//wymaga ustawienia Wire.begin(SDA_PIN, SCL_PIN) wcześniej
taki sam komentarz juz byl w  hpp

2024-03-15 03:25 UTC, Bartosz-Slowik commented on projects/bmp/src/bmp.cpp
> +  //temperatura w Celsjuszach
skip those comments

2024-03-15 03:25 UTC, Bartosz-Slowik commented on projects/bmp/include/bmp.hpp
> +struct Data {
ifc you want to comment the units of measurcements you can put it there

2024-03-15 03:28 UTC, Bartosz-Slowik commented on projects/bmp/src/main.cpp
> +void pseudo_setup() {
Delete the psuedosetup.
move it to setup

2024-03-15 03:30 UTC, Bartosz-Slowik approved these changes

2024-03-15 03:30 UTC, Bartosz-Slowik commented on projects/bmp/test/README
> +- https://docs.platformio.org/en/latest/advanced/unit-testing/index.html
i dont think we need this

2024-03-15 03:30 UTC, Bartosz-Slowik commented on projects/bmp/lib/README
> +- https://docs.platformio.org/page/librarymanager/ldf.html
we dont need this

2024-03-15 03:30 UTC, Bartosz-Slowik commented on projects/bmp/include/README
> +https://gcc.gnu.org/onlinedocs/cpp/Header-Files.html
i dont think we need this

2024-03-15 03:30 UTC, Bartosz-Slowik commented on projects/bmp/.vscode/settings.json
> +}
add this file to gitignore

2024-03-15 03:30 UTC, Bartosz-Slowik commented on projects/bmp/.vscode/extensions.json
> +}
make sure the .vscode folder is in gitignore

2024-03-15 03:34 UTC, PatrykPaluch requested changes

2024-03-15 03:34 UTC, PatrykPaluch commented on projects/bmp/.gitignore
> +.vscode/ipch
Wydaje mi się że cały folder `.vscode` jest do gitignore

```suggestion
.pio/
.vscode/
```

To oznacza że będzie trzeba usunąć z gita już trackowane pliki:

```bash
git rm -r --cached .vscode
```

2024-05-22 17:55 UTC, Bartosz-Slowik commented on projects/bmp/src/bmp.cpp
> +        Serial.println("Nie znaleziono odpowiedniego sensora BMP280, sprawdz okablowanie!");
english

2024-05-22 18:16 UTC, PatrykPaluch approved these changes

2024-05-22 18:18 UTC, merged